### ISSUE TITLE
invalid dates

### ISSUE THREAD

**Issue by gorn** [graemeg/onguard#4]
I have tryed to set up basic date protection following the Example 1 of pdf manual. When I come to "Code Generation" (step 10) and try to click Generate it responds "Invalid start date". I have date in format 2014-03-29 automatically in this field. I suspect that the date format  might be a problem, maybe there is a MaskEdit in this field. In fact I beleive all other date Exit fields have the same problem. When I delete the date manually I am not even allowed to fill in the date with dashes and I can only put in the date consistend with my locale (ie form 29.3.2014) but it does not work eather, giving the same error.

**Comment by graemeg** [comment]
Rather late than never. ;-)  There was a localised to/from text to date issue. This has been fixed ages ago, but I totally forgot to push it to github.
